language: python
python:
    - "3.8"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip3 install -U https://github.com/platformio/platformio-core/archive/develop.zip
    - pio update

script:
    - pio run -e ventilator-ci
